(cl:defpackage test_rosbag-msg
  (:use )
  (:export
   "<RENAMED4>"
   "RENAMED4"
   "<SIMPLEMIGRATED>"
   "SIMPLEMIGRATED"
   "<MIGRATEDMIXED>"
   "MIGRATEDMIXED"
   "<MIGRATEDADDSUB>"
   "MIGRATEDADDSUB"
   "<SUBUNMIGRATED>"
   "SUBUNMIGRATED"
   "<SIMPLE>"
   "SIMPLE"
   "<UNMIGRATED>"
   "UNMIGRATED"
   "<CONSTANTS>"
   "CONSTANTS"
   "<MIGRATEDIMPLICIT>"
   "MIGRATEDIMPLICIT"
   "<MIGRATEDEXPLICIT>"
   "MIGRATEDEXPLICIT"
   "<PARTIALLYMIGRATED>"
   "PARTIALLYMIGRATED"
   "<CONVERGED>"
   "CONVERGED"
  ))

