
(cl:in-package :asdf)

(defsystem "test_roscpp-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :rosgraph_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "TestStringInt" :depends-on ("_package_TestStringInt"))
    (:file "_package_TestStringInt" :depends-on ("_package"))
    (:file "TestWithHeader" :depends-on ("_package_TestWithHeader"))
    (:file "_package_TestWithHeader" :depends-on ("_package"))
    (:file "TestArray" :depends-on ("_package_TestArray"))
    (:file "_package_TestArray" :depends-on ("_package"))
    (:file "TestEmpty" :depends-on ("_package_TestEmpty"))
    (:file "_package_TestEmpty" :depends-on ("_package"))
    (:file "FixedLength" :depends-on ("_package_FixedLength"))
    (:file "_package_FixedLength" :depends-on ("_package"))
    (:file "VariableLengthArrayOfExternal" :depends-on ("_package_VariableLengthArrayOfExternal"))
    (:file "_package_VariableLengthArrayOfExternal" :depends-on ("_package"))
    (:file "EmbeddedVariableLength" :depends-on ("_package_EmbeddedVariableLength"))
    (:file "_package_EmbeddedVariableLength" :depends-on ("_package"))
    (:file "FixedLengthArrayOfExternal" :depends-on ("_package_FixedLengthArrayOfExternal"))
    (:file "_package_FixedLengthArrayOfExternal" :depends-on ("_package"))
    (:file "WithDuration" :depends-on ("_package_WithDuration"))
    (:file "_package_WithDuration" :depends-on ("_package"))
    (:file "WithTime" :depends-on ("_package_WithTime"))
    (:file "_package_WithTime" :depends-on ("_package"))
    (:file "ArrayOfFixedLength" :depends-on ("_package_ArrayOfFixedLength"))
    (:file "_package_ArrayOfFixedLength" :depends-on ("_package"))
    (:file "FixedLengthStringArray" :depends-on ("_package_FixedLengthStringArray"))
    (:file "_package_FixedLengthStringArray" :depends-on ("_package"))
    (:file "WithMemberNamedHeaderThatIsNotAHeader" :depends-on ("_package_WithMemberNamedHeaderThatIsNotAHeader"))
    (:file "_package_WithMemberNamedHeaderThatIsNotAHeader" :depends-on ("_package"))
    (:file "EmbeddedExternal" :depends-on ("_package_EmbeddedExternal"))
    (:file "_package_EmbeddedExternal" :depends-on ("_package"))
    (:file "Constants" :depends-on ("_package_Constants"))
    (:file "_package_Constants" :depends-on ("_package"))
    (:file "VariableLengthStringArray" :depends-on ("_package_VariableLengthStringArray"))
    (:file "_package_VariableLengthStringArray" :depends-on ("_package"))
    (:file "WithHeader" :depends-on ("_package_WithHeader"))
    (:file "_package_WithHeader" :depends-on ("_package"))
    (:file "HeaderNotFirstMember" :depends-on ("_package_HeaderNotFirstMember"))
    (:file "_package_HeaderNotFirstMember" :depends-on ("_package"))
    (:file "CustomHeader" :depends-on ("_package_CustomHeader"))
    (:file "_package_CustomHeader" :depends-on ("_package"))
    (:file "VariableLength" :depends-on ("_package_VariableLength"))
    (:file "_package_VariableLength" :depends-on ("_package"))
    (:file "ArrayOfVariableLength" :depends-on ("_package_ArrayOfVariableLength"))
    (:file "_package_ArrayOfVariableLength" :depends-on ("_package"))
    (:file "EmbeddedFixedLength" :depends-on ("_package_EmbeddedFixedLength"))
    (:file "_package_EmbeddedFixedLength" :depends-on ("_package"))
    (:file "ThroughputMessage" :depends-on ("_package_ThroughputMessage"))
    (:file "_package_ThroughputMessage" :depends-on ("_package"))
    (:file "LatencyMessage" :depends-on ("_package_LatencyMessage"))
    (:file "_package_LatencyMessage" :depends-on ("_package"))
    (:file "PointCloud" :depends-on ("_package_PointCloud"))
    (:file "_package_PointCloud" :depends-on ("_package"))
    (:file "ChannelFloat32" :depends-on ("_package_ChannelFloat32"))
    (:file "_package_ChannelFloat32" :depends-on ("_package"))
    (:file "Point32" :depends-on ("_package_Point32"))
    (:file "_package_Point32" :depends-on ("_package"))
  ))