(cl:in-package test_rosmaster-msg)
(cl:export '(CALLER_ID-VAL
          CALLER_ID
          ORIG_CALLER_ID-VAL
          ORIG_CALLER_ID
          STR-VAL
          STR
          B-VAL
          B
          INT16-VAL
          INT16
          INT32-VAL
          INT32
          INT64-VAL
          INT64
          C-VAL
          C
          UINT16-VAL
          UINT16
          UINT32-VAL
          UINT32
          UINT64-VAL
          UINT64
          FLOAT32-VAL
          FLOAT32
          FLOAT64-VAL
          FLOAT64
          T-VAL
          T
          D-VAL
          D
))