
(cl:in-package :asdf)

(defsystem "test_roslib_comm-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "TypeNameChangeComplex1" :depends-on ("_package_TypeNameChangeComplex1"))
    (:file "_package_TypeNameChangeComplex1" :depends-on ("_package"))
    (:file "SameSubMsg3" :depends-on ("_package_SameSubMsg3"))
    (:file "_package_SameSubMsg3" :depends-on ("_package"))
    (:file "TypeNameChangeArray1" :depends-on ("_package_TypeNameChangeArray1"))
    (:file "_package_TypeNameChangeArray1" :depends-on ("_package"))
    (:file "TypeNameChangeArray2" :depends-on ("_package_TypeNameChangeArray2"))
    (:file "_package_TypeNameChangeArray2" :depends-on ("_package"))
    (:file "FieldNameChange2" :depends-on ("_package_FieldNameChange2"))
    (:file "_package_FieldNameChange2" :depends-on ("_package"))
    (:file "FillSimple" :depends-on ("_package_FillSimple"))
    (:file "_package_FillSimple" :depends-on ("_package"))
    (:file "HeaderTest" :depends-on ("_package_HeaderTest"))
    (:file "_package_HeaderTest" :depends-on ("_package"))
    (:file "FillEmbedTime" :depends-on ("_package_FillEmbedTime"))
    (:file "_package_FillEmbedTime" :depends-on ("_package"))
    (:file "FieldNameChange1" :depends-on ("_package_FieldNameChange1"))
    (:file "_package_FieldNameChange1" :depends-on ("_package"))
    (:file "TypeNameChangeComplex2" :depends-on ("_package_TypeNameChangeComplex2"))
    (:file "_package_TypeNameChangeComplex2" :depends-on ("_package"))
    (:file "SameSubMsg1" :depends-on ("_package_SameSubMsg1"))
    (:file "_package_SameSubMsg1" :depends-on ("_package"))
    (:file "TypeNameChange1" :depends-on ("_package_TypeNameChange1"))
    (:file "_package_TypeNameChange1" :depends-on ("_package"))
    (:file "TypeNameChange2" :depends-on ("_package_TypeNameChange2"))
    (:file "_package_TypeNameChange2" :depends-on ("_package"))
    (:file "ArrayOfMsgs" :depends-on ("_package_ArrayOfMsgs"))
    (:file "_package_ArrayOfMsgs" :depends-on ("_package"))
    (:file "SameSubMsg2" :depends-on ("_package_SameSubMsg2"))
    (:file "_package_SameSubMsg2" :depends-on ("_package"))
  ))