# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from test_rosbag/MigratedAddSub.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import test_rosbag.msg

class MigratedAddSub(genpy.Message):
  _md5sum = "f54ff3b9ba622359fa96ac15d4498153"
  _type = "test_rosbag/MigratedAddSub"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Simple field1
Simple field2
================================================================================
MSG: test_rosbag/Simple
int32 field1 #42"""
  __slots__ = ['field1','field2']
  _slot_types = ['test_rosbag/Simple','test_rosbag/Simple']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       field1,field2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MigratedAddSub, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.field1 is None:
        self.field1 = test_rosbag.msg.Simple()
      if self.field2 is None:
        self.field2 = test_rosbag.msg.Simple()
    else:
      self.field1 = test_rosbag.msg.Simple()
      self.field2 = test_rosbag.msg.Simple()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.field1.field1, _x.field2.field1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.field1 is None:
        self.field1 = test_rosbag.msg.Simple()
      if self.field2 is None:
        self.field2 = test_rosbag.msg.Simple()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.field1.field1, _x.field2.field1,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.field1.field1, _x.field2.field1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.field1 is None:
        self.field1 = test_rosbag.msg.Simple()
      if self.field2 is None:
        self.field2 = test_rosbag.msg.Simple()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.field1.field1, _x.field2.field1,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i = struct.Struct("<2i")
