(cl:defpackage test_rosmaster-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "ROSSRVB"
   "<ROSSRVB-REQUEST>"
   "ROSSRVB-REQUEST"
   "<ROSSRVB-RESPONSE>"
   "ROSSRVB-RESPONSE"
   "ROSSRVA"
   "<ROSSRVA-REQUEST>"
   "ROSSRVA-REQUEST"
   "<ROSSRVA-RESPONSE>"
   "ROSSRVA-RESPONSE"
  ))

