// Generated by gencpp from file topic_tools/MuxSelect.msg
// DO NOT EDIT!


#ifndef TOPIC_TOOLS_MESSAGE_MUXSELECT_H
#define TOPIC_TOOLS_MESSAGE_MUXSELECT_H

#include <ros/service_traits.h>


#include <topic_tools/MuxSelectRequest.h>
#include <topic_tools/MuxSelectResponse.h>


namespace topic_tools
{

struct MuxSelect
{

typedef MuxSelectRequest Request;
typedef MuxSelectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MuxSelect
} // namespace topic_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topic_tools::MuxSelect > {
  static const char* value()
  {
    return "053052240ca985e1f2eedbb0dae9b1f7";
  }

  static const char* value(const ::topic_tools::MuxSelect&) { return value(); }
};

template<>
struct DataType< ::topic_tools::MuxSelect > {
  static const char* value()
  {
    return "topic_tools/MuxSelect";
  }

  static const char* value(const ::topic_tools::MuxSelect&) { return value(); }
};


// service_traits::MD5Sum< ::topic_tools::MuxSelectRequest> should match 
// service_traits::MD5Sum< ::topic_tools::MuxSelect > 
template<>
struct MD5Sum< ::topic_tools::MuxSelectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topic_tools::MuxSelect >::value();
  }
  static const char* value(const ::topic_tools::MuxSelectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_tools::MuxSelectRequest> should match 
// service_traits::DataType< ::topic_tools::MuxSelect > 
template<>
struct DataType< ::topic_tools::MuxSelectRequest>
{
  static const char* value()
  {
    return DataType< ::topic_tools::MuxSelect >::value();
  }
  static const char* value(const ::topic_tools::MuxSelectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topic_tools::MuxSelectResponse> should match 
// service_traits::MD5Sum< ::topic_tools::MuxSelect > 
template<>
struct MD5Sum< ::topic_tools::MuxSelectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topic_tools::MuxSelect >::value();
  }
  static const char* value(const ::topic_tools::MuxSelectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_tools::MuxSelectResponse> should match 
// service_traits::DataType< ::topic_tools::MuxSelect > 
template<>
struct DataType< ::topic_tools::MuxSelectResponse>
{
  static const char* value()
  {
    return DataType< ::topic_tools::MuxSelect >::value();
  }
  static const char* value(const ::topic_tools::MuxSelectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPIC_TOOLS_MESSAGE_MUXSELECT_H
