// Generated by gencpp from file test_rosmaster/RossrvB.msg
// DO NOT EDIT!


#ifndef TEST_ROSMASTER_MESSAGE_ROSSRVB_H
#define TEST_ROSMASTER_MESSAGE_ROSSRVB_H

#include <ros/service_traits.h>


#include <test_rosmaster/RossrvBRequest.h>
#include <test_rosmaster/RossrvBResponse.h>


namespace test_rosmaster
{

struct RossrvB
{

typedef RossrvBRequest Request;
typedef RossrvBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RossrvB
} // namespace test_rosmaster


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_rosmaster::RossrvB > {
  static const char* value()
  {
    return "928fb104d412cd4f5983340b98df1876";
  }

  static const char* value(const ::test_rosmaster::RossrvB&) { return value(); }
};

template<>
struct DataType< ::test_rosmaster::RossrvB > {
  static const char* value()
  {
    return "test_rosmaster/RossrvB";
  }

  static const char* value(const ::test_rosmaster::RossrvB&) { return value(); }
};


// service_traits::MD5Sum< ::test_rosmaster::RossrvBRequest> should match 
// service_traits::MD5Sum< ::test_rosmaster::RossrvB > 
template<>
struct MD5Sum< ::test_rosmaster::RossrvBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_rosmaster::RossrvB >::value();
  }
  static const char* value(const ::test_rosmaster::RossrvBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_rosmaster::RossrvBRequest> should match 
// service_traits::DataType< ::test_rosmaster::RossrvB > 
template<>
struct DataType< ::test_rosmaster::RossrvBRequest>
{
  static const char* value()
  {
    return DataType< ::test_rosmaster::RossrvB >::value();
  }
  static const char* value(const ::test_rosmaster::RossrvBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_rosmaster::RossrvBResponse> should match 
// service_traits::MD5Sum< ::test_rosmaster::RossrvB > 
template<>
struct MD5Sum< ::test_rosmaster::RossrvBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_rosmaster::RossrvB >::value();
  }
  static const char* value(const ::test_rosmaster::RossrvBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_rosmaster::RossrvBResponse> should match 
// service_traits::DataType< ::test_rosmaster::RossrvB > 
template<>
struct DataType< ::test_rosmaster::RossrvBResponse>
{
  static const char* value()
  {
    return DataType< ::test_rosmaster::RossrvB >::value();
  }
  static const char* value(const ::test_rosmaster::RossrvBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_ROSMASTER_MESSAGE_ROSSRVB_H
