(cl:defpackage test_roscpp-srv
  (:use )
  (:export
   "TESTSTRINGSTRING"
   "<TESTSTRINGSTRING-REQUEST>"
   "TESTSTRINGSTRING-REQUEST"
   "<TESTSTRINGSTRING-RESPONSE>"
   "TESTSTRINGSTRING-RESPONSE"
   "BADTESTSTRINGSTRING"
   "<BADTESTSTRINGSTRING-REQUEST>"
   "BADTESTSTRINGSTRING-REQUEST"
   "<BADTESTSTRINGSTRING-RESPONSE>"
   "BADTESTSTRINGSTRING-RESPONSE"
  ))

