// Generated by gencpp from file test_rospy/ConstantsMultiplex.msg
// DO NOT EDIT!


#ifndef TEST_ROSPY_MESSAGE_CONSTANTSMULTIPLEX_H
#define TEST_ROSPY_MESSAGE_CONSTANTSMULTIPLEX_H

#include <ros/service_traits.h>


#include <test_rospy/ConstantsMultiplexRequest.h>
#include <test_rospy/ConstantsMultiplexResponse.h>


namespace test_rospy
{

struct ConstantsMultiplex
{

typedef ConstantsMultiplexRequest Request;
typedef ConstantsMultiplexResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConstantsMultiplex
} // namespace test_rospy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_rospy::ConstantsMultiplex > {
  static const char* value()
  {
    return "bab86066b3f7801cb25df3932f644396";
  }

  static const char* value(const ::test_rospy::ConstantsMultiplex&) { return value(); }
};

template<>
struct DataType< ::test_rospy::ConstantsMultiplex > {
  static const char* value()
  {
    return "test_rospy/ConstantsMultiplex";
  }

  static const char* value(const ::test_rospy::ConstantsMultiplex&) { return value(); }
};


// service_traits::MD5Sum< ::test_rospy::ConstantsMultiplexRequest> should match 
// service_traits::MD5Sum< ::test_rospy::ConstantsMultiplex > 
template<>
struct MD5Sum< ::test_rospy::ConstantsMultiplexRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_rospy::ConstantsMultiplex >::value();
  }
  static const char* value(const ::test_rospy::ConstantsMultiplexRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_rospy::ConstantsMultiplexRequest> should match 
// service_traits::DataType< ::test_rospy::ConstantsMultiplex > 
template<>
struct DataType< ::test_rospy::ConstantsMultiplexRequest>
{
  static const char* value()
  {
    return DataType< ::test_rospy::ConstantsMultiplex >::value();
  }
  static const char* value(const ::test_rospy::ConstantsMultiplexRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_rospy::ConstantsMultiplexResponse> should match 
// service_traits::MD5Sum< ::test_rospy::ConstantsMultiplex > 
template<>
struct MD5Sum< ::test_rospy::ConstantsMultiplexResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_rospy::ConstantsMultiplex >::value();
  }
  static const char* value(const ::test_rospy::ConstantsMultiplexResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_rospy::ConstantsMultiplexResponse> should match 
// service_traits::DataType< ::test_rospy::ConstantsMultiplex > 
template<>
struct DataType< ::test_rospy::ConstantsMultiplexResponse>
{
  static const char* value()
  {
    return DataType< ::test_rospy::ConstantsMultiplex >::value();
  }
  static const char* value(const ::test_rospy::ConstantsMultiplexResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_ROSPY_MESSAGE_CONSTANTSMULTIPLEX_H
