; Auto-generated. Do not edit!


(cl:in-package test_rostopic-msg)


;//! \htmlinclude Arrays.msg.html

(cl:defclass <Arrays> (roslisp-msg-protocol:ros-message)
  ((int8_arr
    :reader int8_arr
    :initarg :int8_arr
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (uint8_arr
    :reader uint8_arr
    :initarg :uint8_arr
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (int32_arr
    :reader int32_arr
    :initarg :int32_arr
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (uint32_arr
    :reader uint32_arr
    :initarg :uint32_arr
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (string_arr
    :reader string_arr
    :initarg :string_arr
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (time_arr
    :reader time_arr
    :initarg :time_arr
    :type (cl:vector cl:real)
   :initform (cl:make-array 0 :element-type 'cl:real :initial-element 0)))
)

(cl:defclass Arrays (<Arrays>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Arrays>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Arrays)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_rostopic-msg:<Arrays> is deprecated: use test_rostopic-msg:Arrays instead.")))

(cl:ensure-generic-function 'int8_arr-val :lambda-list '(m))
(cl:defmethod int8_arr-val ((m <Arrays>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_rostopic-msg:int8_arr-val is deprecated.  Use test_rostopic-msg:int8_arr instead.")
  (int8_arr m))

(cl:ensure-generic-function 'uint8_arr-val :lambda-list '(m))
(cl:defmethod uint8_arr-val ((m <Arrays>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_rostopic-msg:uint8_arr-val is deprecated.  Use test_rostopic-msg:uint8_arr instead.")
  (uint8_arr m))

(cl:ensure-generic-function 'int32_arr-val :lambda-list '(m))
(cl:defmethod int32_arr-val ((m <Arrays>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_rostopic-msg:int32_arr-val is deprecated.  Use test_rostopic-msg:int32_arr instead.")
  (int32_arr m))

(cl:ensure-generic-function 'uint32_arr-val :lambda-list '(m))
(cl:defmethod uint32_arr-val ((m <Arrays>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_rostopic-msg:uint32_arr-val is deprecated.  Use test_rostopic-msg:uint32_arr instead.")
  (uint32_arr m))

(cl:ensure-generic-function 'string_arr-val :lambda-list '(m))
(cl:defmethod string_arr-val ((m <Arrays>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_rostopic-msg:string_arr-val is deprecated.  Use test_rostopic-msg:string_arr instead.")
  (string_arr m))

(cl:ensure-generic-function 'time_arr-val :lambda-list '(m))
(cl:defmethod time_arr-val ((m <Arrays>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_rostopic-msg:time_arr-val is deprecated.  Use test_rostopic-msg:time_arr instead.")
  (time_arr m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Arrays>) ostream)
  "Serializes a message object of type '<Arrays>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'int8_arr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    ))
   (cl:slot-value msg 'int8_arr))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'uint8_arr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'uint8_arr))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'int32_arr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'int32_arr))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'uint32_arr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) ele) ostream))
   (cl:slot-value msg 'uint32_arr))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'string_arr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'string_arr))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'time_arr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__sec (cl:floor ele))
        (__nsec (cl:round (cl:* 1e9 (cl:- ele (cl:floor ele))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream)))
   (cl:slot-value msg 'time_arr))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Arrays>) istream)
  "Deserializes a message object of type '<Arrays>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'int8_arr) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'int8_arr)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'uint8_arr) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'uint8_arr)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'int32_arr) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'int32_arr)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'uint32_arr) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'uint32_arr)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'string_arr) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'string_arr)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'time_arr) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'time_arr)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Arrays>)))
  "Returns string type for a message object of type '<Arrays>"
  "test_rostopic/Arrays")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Arrays)))
  "Returns string type for a message object of type 'Arrays"
  "test_rostopic/Arrays")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Arrays>)))
  "Returns md5sum for a message object of type '<Arrays>"
  "c5a1f18379b10bdd4df210944f6007a4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Arrays)))
  "Returns md5sum for a message object of type 'Arrays"
  "c5a1f18379b10bdd4df210944f6007a4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Arrays>)))
  "Returns full string definition for message of type '<Arrays>"
  (cl:format cl:nil "#for rostopic tests~%int8[] int8_arr~%uint8[] uint8_arr~%int32[] int32_arr~%uint32[] uint32_arr~%string[] string_arr~%time[] time_arr~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Arrays)))
  "Returns full string definition for message of type 'Arrays"
  (cl:format cl:nil "#for rostopic tests~%int8[] int8_arr~%uint8[] uint8_arr~%int32[] int32_arr~%uint32[] uint32_arr~%string[] string_arr~%time[] time_arr~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Arrays>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'int8_arr) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'uint8_arr) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'int32_arr) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'uint32_arr) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'string_arr) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'time_arr) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Arrays>))
  "Converts a ROS message object to a list"
  (cl:list 'Arrays
    (cl:cons ':int8_arr (int8_arr msg))
    (cl:cons ':uint8_arr (uint8_arr msg))
    (cl:cons ':int32_arr (int32_arr msg))
    (cl:cons ':uint32_arr (uint32_arr msg))
    (cl:cons ':string_arr (string_arr msg))
    (cl:cons ':time_arr (time_arr msg))
))
